version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  med-search:
    container_name: med-search
    image: med-search:latest
    ports:
      - '18700-18790:8900'
    depends_on:
      - postgres
      - redis
networks:
  med-searcch-network:
    driver: bridge
